apiVersion: v1
kind: Namespace
metadata:
  name: web-ui
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: web-team
  labels:
    istio-injection: enabled
---
apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: rollouttest
  namespace: web-team
spec:
  hosts:
    - rollouts.web-ui-team.solo-io.mesh
  services:
    - labels:
        app: rollouts-demo
  ports:
    - number: 8080
      protocol: HTTP
      targetPort:
        number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo
  namespace: web-ui
  labels:
    app: rollouts-demo
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: rollouts-demo
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: web-ui
spec:
  replicas: 5
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {duration: 10}
        - setWeight: 60
        - pause: {duration: 10}
        - setWeight: 80
        - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:blue
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m